#!/bin/bash

printHelpAndExit() {
    echo "Usage: ${0##*/} <coolfile> <sample name>"
    echo "  coolfile: Input Hi-C data (.cool format)"
    echo "  sample name: Name of the sample (also used for the output file name)"
#    echo "  resolution: resolution of contact matrix"
#    echo "  peak: BED format peak file to estimate compartment (e.g. H3K27ac)"
   exit 0
}

if [ $# -ne 2 ]; then
  printHelpAndExit
  exit 1
fi

coolfile=$1
sample_name=$2
#peak=$3
#resolution=$3

Rdir=$(cd $(dirname $0) && pwd)

Rscript $Rdir/compartment_strength_GENOVA.R $coolfile $sample_name #$peak
