#!/bin/bash

printHelpAndExit() {
    echo "Usage: ${0##*/} <outputdir> <matrix> <PC1file> <start> <end> <resolution>"
    echo "  <outputdir>: directory where the output files are generaged"
    echo "  <matrix>: normalized dense matrix"
    echo "  <PC1file>: compartment file (bed format)"
    echo "  <resolution>: resolution of the matrix"
    echo "  Example:"
    echo "     ${0##*/} pastis/25000/chr21 intrachromosomal/25000/observed.SCALE.ch21.matrix.gz Eigen/25000/Compartment.SCALE.chr21.All.bed 24000000 32000000 25000"
    exit 0
}

if [ $# -ne 6 ]; then
    printHelpAndExit
fi

odir=$1
Matrix=$2
Eigen=$3
start=$4
end=$5
resolution=$6

echo "Start 3D modeling by PASTIS..."

s1=$(( $start / $resolution ))
e1=$(( $end / $resolution ))
#Matrix=$odir/Matrix/intrachromosomal/$resolution/observed.$norm.$chr.matrix.gz
#Eigen=$odir/Eigen/$resolution/Compartment.$norm.$chr.All.bed
#dir=$odir/pastis/${resolution}/$chr

mkdir -p $odir
micromamba run -n pastis matrix2npy.py $Matrix $odir/Matrix.npy --start1 $s1 --end1 $e1 --start2 $s1 --end2 $e1

config=$odir/config.ini
echo "[all]"               > $config
echo "verbose: 1"          >> $config
echo "max_iter: 1000"      >> $config
echo "normalize: True"     >> $config
echo "output_name: $chr-$start-$end" >> $config
echo "counts: Matrix.npy"  >> $config

micromamba run -n pastis pastis-pm2 $odir
addCompartment4pastis.pl $odir/PM2.$start-$end.pdb $Eigen $s1
addChain4pastis.pl $odir/PM2.$start-$end.pdb.addCompartment.pdb
