#!/bin/bash

printHelpAndExit() {
    echo "Usage: ${0##*/} <outputdir> <hic> <chr> <start> <end> <resolution> <norm>"
    echo "  <outputdir>: directory where the output files are generaged"
    echo "  <hic>: .hic file"
    echo "  <chr> <start> <end>: chromosome, start and end positions for simulation"
    echo "  <resolution>: resolution of the matrix"
    echo "  <norm>: normalization type (NONE|VC|VC_SQRT|KR|SCALE)"
    echo "  Example:"
    echo "     ${0##*/} JuicerResults/sample1 JuicerResults/sample1/aligned/inter_30.hic chr21 24000000 32000000 1000000 SCALE"
    exit 0
}

if [ $# -ne 7 ]; then
    printHelpAndExit
fi

odir=$1
hic=$2
chr=$3
start=$4
end=$5
resolution=$6
norm=$7

echo "Start 4D simulation by PHi-C..."
cell=$start-$end
dir=$odir/4dmodel/$resolution/$chr/
mkdir -p $dir
strawMatrixFromHiC.py $hic $dir/$cell.txt $chr --start $start --end $end --dense
phic preprocessing --input $dir/$cell.txt --res $resolution --plt-max-c 0.1
#for prefix in C_normalized P_normalized
#do
#    convert -define registry:temporary-path="$dir/tmp" $(pwd)/$dir/$cell/$prefix.svg $(pwd)/$dir/$cell/$prefix.png
#done
phic optimization --name $dir/$cell
phic plot-optimization --name $dir/$cell --res $resolution --plt-max-c 0.1 \
     --plt-max-k-backbone 1.0 --plt-max-k 0.1 --plt-k-dis-bins 200 --plt-max-k-dis 100
phic dynamics --name $dir/$cell --interval 100 --frame 1000
phic sampling --name $dir/$cell --sample 1000
echo "done."

echo "Estimate rheology..."
phic rheology --name $dir/$cell
phic plot-compliance --name $dir/$cell --plt-upper 0 --plt-lower -3 --plt-max-log 1.3 --plt-min-log -0.3
phic plot-modulus    --name $dir/$cell --plt-upper 0 --plt-lower -3 --plt-max-log 0.4 --plt-min-log -1.2
phic plot-tangent    --name $dir/$cell --plt-upper 0 --plt-lower -3 --plt-max-log 0.2
echo "done."

echo "Generate Hi-C map movie..."
nframe=1000
N=`echo $start $end $resolution | awk '{printf ("%d",($2-$1)/$3 +1)}'`
plot_distance_map.py $dir/$cell/data_dynamics/sample0.xyz $N $nframe $dir/$cell/distance_map/
ffmpeg -framerate 24 -i $dir/$cell/distance_map/frame_%04d.jpg -pix_fmt yuv420p \
      -c:v libx264 -preset slow -crf 24 -r 24 \
      -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" \
      $dir/$cell/distance_map/movie.mp4
echo "done."
