#!/bin/bash -e
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <hicfile> <odir>" 1>&2
    echo '   <hicfile>: .hic file genreated by Juicer' 1>&2
    echo "   <odir> : output directory"
    echo '   Options:' 1>&2
    echo "      -g genometable : genome table file (describing the chromosome length)"
    echo "      -n [NONE|VC|VC_SQRT|KR|SCALE] : normalization type (default: SCALE)"
    echo '      -a <refFlat>: gene annotation file' 1>&2
    echo '      -r resolutions : resolutions for 1D metrics calculation (default: "25000 50000 100000", should be quoted and separated by spaces)' 1>&2
    echo '      -p ncore: number of CPUs (default: 32)' 1>&2
    echo '      -o: Use older version of juicer_tools.jar for old .hic files (juicer_tools.1.9.9_jcuda.0.8.jar, default: juicer_tools.1.22.01.jar)' 1>&2
    echo '   Example:' 1>&2
    echo "      $cmdname -g genometable.hg38.txt -a refFlat.hg38.txt Hap1-A/inter_30.hic Hap1-A" 1>&2
}

gt=""
ncore=32

norm="SCALE"
resolutions="25000 50000 100000"
gene=""
useoldversion=""
while getopts g:n:r:a:p:o option; do
    case ${option} in
	g) gt=${OPTARG} ;;
	n) norm=${OPTARG} ;;
	r) resolutions=${OPTARG} ;;
	a) gene=${OPTARG} ;;
    p) ncore=${OPTARG} ;;
    o) useoldversion="-o" ;;
    \?) 
        echo "Invalid option: -$OPTARG" >&2
        usage
        exit 1
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

hic=$1
odir=$2

if test "$gt" = ""; then
    echo "Error: specify genome table (-g)."
    exit 0
fi

if [[ ${odir} =~ ^/.+$ ]]; then
    odir=$odir
else
    odir=$(pwd)/$odir
fi

ex(){ echo $1; eval $1; }

for resolution in $resolutions
do
    # Contact matrix
    echo "generate Matrix..."
    ex "makeMatrix_intra.sh $useoldversion $norm $odir $hic $resolution $gt"
    # InsulationScore
    echo "calculate Insulation score.."
    ex "makeInslationScore.sh $norm $odir $resolution $gt"

    # Eigen
    if test "$gene" = ""; then
       echo "gene file is not specified. PC1 calculation is skipped."
    else
       echo "calculate PC1.."
       ex "makeEigen.sh -p $ncore $norm $odir $hic $resolution $gt $gene"
    fi
done

# TAD
echo "call TAD..."
ex "juicer_callTAD.sh $useoldversion $norm $odir $hic $gt"

# Loop
echo "call loops..."
ex "call_HiCCUPS.sh $useoldversion $norm $odir $hic"
