FROM rnakato/custardpy_r:3.4.1 AS base
LABEL maintainer="Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

# For sorting, LC_ALL is C
ENV LC_ALL=C
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

WORKDIR /opt/
USER root

SHELL ["/bin/bash", "-c"]

# BWA version 0.7.17
COPY bwa-0.7.17.tar.bz2 bwa-0.7.17.tar.bz2
RUN tar xvfj bwa-0.7.17.tar.bz2 \
    && cd bwa-0.7.17 \
    && make \
    && cd .. \
    && rm bwa-0.7.17.tar.bz2

# Chromap 0.3.2
COPY chromap-0.3.2.tar.gz chromap-0.3.2.tar.gz
RUN tar zxvf chromap-0.3.2.tar.gz \
    && cd chromap-0.3.2 \
    && make \
    && cp chromap /usr/local/bin/ \
    && rm -rf /opt/chromap-0.3.2 /opt/chromap-0.3.2.tar.gz

# Bowtie 1.3.1
COPY bowtie-1.3.1-linux-x86_64.zip bowtie-1.3.1-linux-x86_64.zip
RUN unzip bowtie-1.3.1-linux-x86_64.zip \
    && rm bowtie-1.3.1-linux-x86_64.zip

# Bowtie2.4.5
COPY bowtie2-2.4.5-linux-x86_64.zip bowtie2-2.4.5-linux-x86_64.zip
RUN unzip bowtie2-2.4.5-linux-x86_64.zip \
    && rm bowtie2-2.4.5-linux-x86_64.zip

# pairsqc
RUN wget --progress=dot:giga https://github.com/4dn-dcic/pairsqc/archive/0.2.3.tar.gz \
    && tar -xzf 0.2.3.tar.gz \
    && rm 0.2.3.tar.gz \
    && ln -s /opt/pairsqc-*/ /opt/pairsqc

# BEDtools
ENV v=2.31.0
COPY bedtools-$v.tar.gz bedtools-$v.tar.gz
RUN tar zxvf bedtools-$v.tar.gz \
    && cd bedtools2 && make \
    && rm /opt/bedtools-$v.tar.gz

# HiCUP
COPY HiCUP-0.9.2.tar.gz HiCUP-0.9.2.tar.gz
RUN tar zxvf HiCUP-0.9.2.tar.gz \
    && rm HiCUP-0.9.2.tar.gz

# ChIAPoP
COPY ChIAPoP_0.99.9.7.tar.gz ChIAPoP_0.99.9.7.tar.gz
RUN R CMD INSTALL ChIAPoP_0.99.9.7.tar.gz \
    && rm ChIAPoP_0.99.9.7.tar.gz

RUN mkdir /opt/restriction_sites/

## Cooler restriction sites
RUN wget --quiet https://x.gd/qH1Lw -O Cooler-restriction_sites.tar.gz \
    && tar zxvf Cooler-restriction_sites.tar.gz \
    && mv Cooler-restriction_sites /opt/restriction_sites/ \
    && rm Cooler-restriction_sites.tar.gz

## HiC-Pro restriction sites
RUN wget --quiet https://x.gd/0DJOX -O HiCPro-restriction_sites.tar.gz \
    && tar zxvf HiCPro-restriction_sites.tar.gz \
    && mv HiCPro-restriction_sites /opt/restriction_sites/ \
    && rm HiCPro-restriction_sites.tar.gz

# Juicer v1.6 and Juicer tools v1.22.01
COPY juicer-1.6 /opt/juicer
#COPY juicer_tools.1.22.01.jar /opt/juicer/scripts/common/juicer_tools.jar
COPY juicer_tools.1.22.01.jar /opt/juicer/juicer_tools.1.22.01.jar
COPY juicer_tools.1.9.9_jcuda.0.8.jar /opt/juicer/juicer_tools.1.9.9_jcuda.0.8.jar
COPY juicer_tools.2.20.00.jar /opt/juicer/juicer_tools.2.20.00.jar
RUN wget --quiet https://x.gd/5ND8F -O Juicer-restriction_sites.tar.gz \
    && tar zxvf Juicer-restriction_sites.tar.gz \
    && mv Juicer-restriction_sites /opt/restriction_sites/ \
    && rm Juicer-restriction_sites.tar.gz

COPY motiffiles motiffiles
RUN unpigz /opt/motiffiles/*gz
COPY Juicebox.jar /opt/Juicebox.jar
