#! /usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import matplotlib.pyplot as plt
import seaborn as sns
from custardpy.HiCmodule import JuicerMatrix
from custardpy.InsulationScore import getInsulationScoreOfMultiSample
from custardpy.generateCmap import *
from custardpy.loadData import *
from custardpy.PlotModule import *

#import pdb

def main():
    parser = argparse.ArgumentParser()
    tp = lambda x:list(map(str, x.split(':')))
    parser.add_argument("input", help="<Input directory>:<label>", type=tp, nargs='*')
    parser.add_argument("-o", "--output", help="Output prefix", type=str, default="output")
    parser.add_argument("-c", "--chr", help="chromosome", type=str)
    parser.add_argument("--log", help="logged count", action='store_true')
    parser.add_argument("--type", help="normalize type (default: SCALE)", type=str, default="SCALE")
    parser.add_argument("-r", "--resolution", help="resolution (default: 25000)", type=int, default=25000)
    parser.add_argument("-s", "--start", help="start bp (default: 0)", type=int, default=0)
    parser.add_argument("-e", "--end",   help="end bp (default: 1000000)", type=int, default=1000000)
    parser.add_argument("--vmax", help="max value of color bar (default: 50)", type=int, default=50)
    parser.add_argument("--vmin", help="min value of color bar (default: 0)", type=int, default=0)
    parser.add_argument("-d", "--vizdistancemax", help="max distance in heatmap", type=int, default=0)
    parser.add_argument("--xsize", help="xsize for figure", type=int, default=10)
    parser.add_argument("--ysize", help="ysize (* times of samples)", type=int, default=3)

    args = parser.parse_args()
#    print(args)

    dirs = []
    labels = []
    for input in args.input:
        dirs.append(input[0])
        if (len(input) >1):
            labels.append(input[1])
        else:
            labels.append("")


    if len(dirs) != 2:
        print ("Error: specify two samples (-i).")
        exit()
    if args.chr is None:
        print ("Error: specify chromosome (-c).")
        exit()


    chr = args.chr
    resolution = args.resolution
    type = args.type
    figstart = args.start
    figend = args.end
    s = int(figstart / resolution)
    e = int(figend   / resolution)
    vmax = args.vmax
    vmin = args.vmin
    if (args.log):
        vmax = np.log1p(vmax)
        vmin = np.log1p(vmin)

    print (chr)
    print (resolution)
    samples = []
    tads = []
    loops = []
    for dir in dirs:
       observed = dir + "/Matrix/intrachromosomal/" + str(resolution) + "/observed."  + type + "." + chr + ".matrix.gz"
       samples.append(JuicerMatrix("RPM", observed, resolution))
       tadfile = dir + "/TAD/" + type + "/" + str(resolution) + "_blocks.bedpe"
       print(tadfile)
       tads.append(loadTADs(tadfile, chr, start=figstart, end=figend))
       loopfile = dir + "/loops/"  + type + "/merged_loops.bedpe"
       print(loopfile)
       loops.append(loadloops(loopfile, chr, start=figstart, end=figend))

    ### Plot
    drawHeatmapTrianglePair(plt, samples[0].getmatrix(), samples[1].getmatrix(),
                            resolution,
                            figstart=figstart, figend=figend,
                            tads=tads[0], loops=loops[0],
                            tads2=tads[1], loops2=loops[1],
                            vmax=vmax, vmin=vmin, distancemax=args.vizdistancemax,
                            label=labels[0] + "(upper)-" + labels[1] + "(lower)", xticks=True)

    plt.savefig(args.output + ".pdf")

if(__name__ == '__main__'):
    main()
